//
// Created by mateusz on 14.11.22.
//

#ifndef TRAVELLING_SALESMAN_PROBLEM_INSTANCEREADERFILE_H
#define TRAVELLING_SALESMAN_PROBLEM_INSTANCEREADERFILE_H


class InstanceReaderFile {

};


#endif //TRAVELLING_SALESMAN_PROBLEM_INSTANCEREADERFILE_H
