name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/backend
    runs-on: ubuntu-latest
    steps:
      - name: Install Boost
        run: sudo apt-get install libboost-all-dev

      - name: Install Websocketpp
        run: cd lib/websocketpp && cmake . && sudo make install && cd ../..

      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure
